### ISSUE TITLE
Research Metric to Compare Fixed Image with Final Warped Image

### ISSUE THREAD

**Issue by J-Yash** [cns-iu/ccf-research-r2ui#19]

**Comment by katyb** [comment]
Please ask Jim Gee's team.

**Comment by J-Yash** [comment]
After meeting with Jim Gee and Nick: It is an open problem and there isn't really a good way to do this. You could simply analyze the registration visually. Cross-correlation and Mutual Information not good metrics. Important to define what is a "good enough" registration for the particular use-case.

**Comment by andreasbueckle** [comment]
Glad to see this conversation about finding a good metric happen. Kind of surprised they do not have a fitting one we can use out of the box. Could we run a pixel analysis of the result image and compare RGB values/brightness of the registration "rings"?
